### ISSUE TITLE
Feature: Resource tracking global view

### ISSUE THREAD

**Issue by Sispheor** [HewlettPackard/squest#37]
The resource tracking feature is in progress.
We have so far:

- CRUD on resource group
- CRUD on resource pool

We need to add a view that give a visual map of resource group with link on attributes of a resource pool.

The idea is to generate a page with [graphviz](https://graphviz.org/).

Example of code with dot language (can be tested in the online editor here)
```
digraph {
  node [shape=plaintext]
    rg1 [label=
    <
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
      <TR>
          <TD COLSPAN="12">Resource Group</TD>
      </TR>
      <TR>
          <TD COLSPAN="6">Name</TD>
          <TD COLSPAN="6">Server</TD>
      </TR>
      <TR>
          <TD COLSPAN="6">Resource</TD>
          <TD COLSPAN="6">34</TD>
      </TR>
      <TR>
          <TD COLSPAN="12">Attributes</TD>
      </TR>
      <TR>
        <TD COLSPAN="6">Name</TD>
        <TD COLSPAN="6">Total</TD>
      </TR>
      <TR>
        <TD PORT="rg1_vCPU" COLSPAN="6">vCPU</TD>
        <TD COLSPAN="6">60</TD>
      </TR>
      <TR>
        <TD PORT="rg1_memory" COLSPAN="6">Memory</TD>
        <TD COLSPAN="6">34</TD>
      </TR>
    </TABLE>
    >
    ];
    
  node [shape=plaintext]
    rp1 [label=
    <
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
      <TR>
          <TD COLSPAN="12">Resource Pool</TD>
      </TR>
      <TR>
          <TD COLSPAN="6">Name</TD>
          <TD COLSPAN="6">vCenter</TD>
      </TR>
      <TR>
          <TD COLSPAN="12">Attributes</TD>
      </TR>
      <TR>
        <TD COLSPAN="3">name</TD>
        <TD COLSPAN="3">Produced</TD>
        <TD COLSPAN="3">Consumed</TD>
        <TD COLSPAN="3">Available</TD>
      </TR>
      <TR>
        <TD PORT="rp1_vCPU" COLSPAN="3">vCPU</TD>
        <TD COLSPAN="3">40</TD>
        <TD COLSPAN="3">30</TD>
        <TD COLSPAN="3">10</TD>
      </TR>
      <TR>
        <TD PORT="rp1_memory" COLSPAN="3">Memory</TD>
        <TD COLSPAN="3">100</TD>
        <TD COLSPAN="3">20</TD>
        <TD COLSPAN="3">80</TD>
      </TR>
    </TABLE>
    >
    ]; 
    
    rg2 [label=
    <
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
      <TR>
          <TD COLSPAN="12">Resource Group</TD>
      </TR>
      <TR>
          <TD COLSPAN="6">Name</TD>
          <TD COLSPAN="6">VM</TD>
      </TR>
      <TR>
          <TD COLSPAN="6">Resource</TD>
          <TD COLSPAN="6">34</TD>
      </TR>
      <TR>
          <TD COLSPAN="12">Attributes</TD>
      </TR>
      <TR>
        <TD COLSPAN="6">Name</TD>
        <TD COLSPAN="6">Total</TD>
      </TR>
      <TR>
        <TD PORT="rg2_vCPU" COLSPAN="6">vCPU</TD>
        <TD COLSPAN="6">60</TD>
      </TR>
      <TR>
        <TD PORT="rg2_memory" COLSPAN="6">Memory</TD>
        <TD COLSPAN="6">34</TD>
      </TR>
    </TABLE>
    >
    ];
    
    node [shape=plaintext]
    rg3 [label=
    <
    <TABLE BORDER="0" CELLBORDER="1" CELLSPACING="0">
      <TR>
          <TD COLSPAN="12">Resource Group</TD>
      </TR>
      <TR>
          <TD COLSPAN="3">Name</TD>
          <TD COLSPAN="3">Resources</TD>
          <TD COLSPAN="3">vCPU</TD>
          <TD COLSPAN="3">Memory</TD>
      </TR>
      <TR>
        <TD COLSPAN="3">vCenter</TD>
        <TD COLSPAN="3">23</TD>
        <TD COLSPAN="3">30</TD>
        <TD COLSPAN="3">45</TD>
      </TR>
    </TABLE>
    >
    ];
    
    rg1:rg1_vCPU -> rp1:rp1_vCPU [color = green]
    rg1:rg1_memory -> rp1:rp1_memory [color = green]
    
   rp1:rp1_vCPU  -> rg2:rg2_vCPU [color = red]
   rp1:rp1_memory -> rg2:rg2_memory [color = red]
    
}
```

Here is the result:
![image](https://user-images.githubusercontent.com/2573405/124785468-2ae11c00-df47-11eb-814d-5a081d0fc3d0.png)

Todo:

- [x] New link from the sidebar that point to this new page
- [x] Method that generate the view from current data in the DB
- [x] Color on attribute links (red when consumer, green when producer)
- [x] On resource group: Link on the number of resource that point to resource_group_resource_list view
- [x] On resource pool: Link on producer that point to resource_pool_attribute_producer_list
- [x] On resource pool: Link on consumer that point to resource_pool_attribute_consumer_list
- [x] Add background color on TD element with same color as our bootstrap framework

**Comment by Sispheor** [comment]
New minimalist version POC
![image](https://user-images.githubusercontent.com/2573405/124791282-371ba800-df4c-11eb-8af9-5db64c9ca5bc.png)

**Comment by Sispheor** [comment]
Done and merged in dev
